src/easyoa/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()
from settings import HERE
 
urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'easyoa.oa.views.index',),
    url(r'^resources/(?P<path>.*)$', 'django.views.static.serve',{'document_root': HERE+'/htdocs/resources/'}),
    url(r'^menu/getAccordionItem$', 'easyoa.oa.views.getAccordionItem'),
    url(r'^menu/getAllTreeNode/(?P<parentId>.*)$', 'easyoa.oa.views.getAllTreeNode'),
    url(r'^department/$','easyoa.oa.views.department'),
    url(r'^department/(?P<action>.*)$','easyoa.oa.views.departmentAction'),
    url(r'^aclUser/$','easyoa.oa.views.aclUser'),
    url(r'^aclUser/(?P<action>.*)$','easyoa.oa.views.aclUserAction'),

    # Uncomment the admin/doc line below to enable admin documentation:
    #url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

src/easyoa/core/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User

class BaseModel(models.Model):
    createdate=models.DateTimeField(u'创建时间',auto_now_add=True)
    modifydate=models.DateTimeField(u'更新时间',auto_now=True)
    author=models.ForeignKey(User,related_name='%(app_label)s_%(class)s_author_related',verbose_name=u'修改人',null=True)
    class Meta:
        abstract = True
    def __unicode__(self):
        if hasattr(self,'name'):
            return self.name
        else:
            return str(self.id)

src/easyoa/oa/models.py
# -*- coding: utf-8 -*-
from django.db import models
from easyoa.core.models import BaseModel

class Department(BaseModel):
    code=models.CharField(u'编码',max_length=100)
    name=models.CharField(u'名称',max_length=100)
    class Meta:
        verbose_name = u"部门"
        verbose_name_plural = u"部门"  

class AclUser(BaseModel):
    code=models.CharField(u'编码',max_length=100)
    name=models.CharField(u'名称',max_length=100)
    department=models.ForeignKey(Department,verbose_name=u'部门')
    birthday=models.DateField(u'生日',)
    class Meta:
        verbose_name = u"用户"
        verbose_name_plural = u"用户"   

src/easyoa/oa/forms.py
# -*- coding: utf-8 -*-
from django.forms import CharField,FileField,TextInput,Textarea,ModelForm,Select
from .models import *

class DepartmentForm(ModelForm):
    class Meta:
        model = Department	
        exclude = ['createdate','modifydate','author']

class AclUserForm(ModelForm):
    class Meta:
        model = AclUser	
        exclude = ['createdate','modifydate','author']
        widgets = {
            'birthday': TextInput(attrs={'class': 'easyui-datebox',}),
            'department': Select(attrs={'class': 'easyui-combogrid','data-options': '''
            	panelWidth: 500,
            	url: '/department/find',
            	idField: 'id',
            	textField: 'name',
            	mode: 'local',
            	fitColumns: true,
            	columns: [[
                    {field: 'id', title: 'Item ID', width: 60, checkbox: true},
                    {field: 'code', title: '部门编码', width: 80},
                    {field: 'name', title: '部门名称', align: 'right', width: 60}
                ]],
            	filter: function(q, row) {
                	return (row.code != null && row.code.indexOf(q) >= 0 || row.name != null && row.name.indexOf(q) >= 0);
            	}'''
            })
        }

src/easyoa/core/views.py
# -*- coding: utf-8 -*-

from django.db.models.query import QuerySet

def json(obj,fields=[]):
    if isinstance(obj,QuerySet):
        if fields==[]:
           return [dict(zip([f.name for f in o._meta.fields],[unicode(getattr(o,f.name)) for f in o._meta.fields])) for o in obj]
        return [dict(zip([f.name for f in fields],[unicode(getattr(o,f.name)) for f in fields])) for o in obj]
    else:
        if fields==[]:
           return dict(zip([f.name for f in obj._meta.fields],[unicode(getattr(obj,f.name)) for f in obj._meta.fields]))
        return dict(zip([f.name for f in fields],[unicode(getattr(obj,f.name)) for f in fields]))

def query(cls,request,queryDict):
    if request.GET.has_key('rows'):
        rows=int(request.GET['rows'])
        page=int(request.GET['page'])
    query={}
    for key in queryDict.keys():
        if request.GET.has_key(queryDict[key]):
            query['%s__contains'%key]=request.GET[queryDict[key]]
    total=cls.objects.filter(**query).count()
    if request.GET.has_key('rows'): 
        objs=cls.objects.filter(**query)[(page-1)*rows:page*rows]
    else: 
        objs=cls.objects.filter(**query)
    return {'total':total,'rows':json(objs)}

src/easyoa/oa/views.py
# -*- coding: utf-8 -*-

from django.shortcuts import render_to_response
from django import forms
from django.template import RequestContext
from django.http import HttpResponse, HttpResponseRedirect
from django.template.loader import get_template
from django.utils import simplejson
from .models import *
from .forms import *
from easyoa.core.views import json,query
import xml.dom.minidom  
from easyoa.settings import HERE

def index(request):
    return render_to_response('index.html')

def getAccordionItem(request):
    doc = xml.dom.minidom.parse(HERE+'/oa/modules.xml')  
    data=[dict(node.attributes.items()) for node in doc.getElementsByTagName("sub_system")]
    return HttpResponse(simplejson.dumps(data))

def getAllTreeNode(request,parentId):
    doc = xml.dom.minidom.parse(HERE+'/oa/modules.xml')  
    node = doc.getElementById(parentId)
    data=[dict(zip(['pid','id','text','iconCls','attributes'], [m.parentNode.getAttribute('id'),m.getAttribute('id'), \
         m.getAttribute('text'),m.getAttribute('iconCls'),{'url':m.getAttribute('url')}])) \
         for m in node.getElementsByTagName("module")]
    return HttpResponse(simplejson.dumps(data))

def department(request):
    return render_to_response('department.html')
        
def departmentAction(request,action):
    if action=='query': return render_to_response('department_query.html')
    if action=='find':
        data=query(Department,request,{'name':'departmentName'})
        return HttpResponse(simplejson.dumps(data))
    if action=='add':
        form = DepartmentForm(request.POST or None)
        url = '/department/add'
        if request.method == "POST":
            if form.is_valid():
                o=form.save()
                data={'success':True,'msg':"成功增加一笔部门资料。",'obj':json(o),'isAdd':True}
                return HttpResponse(simplejson.dumps(data))
        t = get_template('department_pop.html')
        c = RequestContext(request,locals())
        return HttpResponse(t.render(c))
    if action=='del':
        ids=request.GET['ids']
        for pk in ids.split(","):
            Department.objects.get(pk=pk).delete()
        data={'success':True,'msg':"成功删除部门资料。",'obj':None}
        return HttpResponse(simplejson.dumps(data))
    if action.startswith('edit')>0: 
        pk=action.split("/")[-1]
        instance = Department.objects.get(pk=pk)
        form = DepartmentForm(request.POST or None, instance = instance) 
        url = '/department/edit/'+pk
        if request.method == "POST":
            if form.is_valid():
                o=form.save()
                data={'success':True,'msg':"成功修改一笔部门资料。",'obj':json(o),'isAdd':False}
                return HttpResponse(simplejson.dumps(data))
        t = get_template('department_pop.html')
        c = RequestContext(request,locals())
        return HttpResponse(t.render(c))       

def aclUser(request):
    return render_to_response('aclUser.html')
        
def aclUserAction(request,action):
    if action=='find':
        data=query(AclUser,request,{'name':'userName'})
        return HttpResponse(simplejson.dumps(data))
    if action=='add':
        form = AclUserForm(request.POST or None)
        url = '/aclUser/add'
        if request.method == "POST":
            if form.is_valid():
                o=form.save()
                data={'success':True,'msg':"成功增加一笔用户资料。",'obj':json(o),'isAdd':True}
                return HttpResponse(simplejson.dumps(data))
        t = get_template('aclUser_pop.html')
        c = RequestContext(request,locals())
        return HttpResponse(t.render(c))
    if action=='del':
        ids=request.GET['ids']
        for pk in ids.split(","):
            AclUser.objects.get(pk=pk).delete()
        data={'success':True,'msg':"成功删除用户资料。",'obj':None}
        return HttpResponse(simplejson.dumps(data))
    if action.startswith('edit')>0: 
        pk=action.split("/")[-1]
        instance = AclUser.objects.get(pk=pk)
        form = AclUserForm(request.POST or None, instance = instance) 
        url = '/aclUser/edit/'+pk
        if request.method == "POST":
            if form.is_valid():
                o=form.save()
                data={'success':True,'msg':"成功修改一笔用户资料。",'obj':json(o),'isAdd':False}
                return HttpResponse(simplejson.dumps(data))
        t = get_template('aclUser_pop.html')
        c = RequestContext(request,locals())
        return HttpResponse(t.render(c))       

src/easyoa/templates/aclUser.html
{% extends "base.html" %}

{% block js %}
        <script type="text/javascript">
            function searchUser() {
                $('#user_datagrid').datagrid('load', serializeObject($('#user_searchForm')));
            }
            
            function clear() {
                $('#admin_yhgl_layout input[name=userName]').val('');
                $('#user_datagrid').datagrid('load', {});
            }
            
            function addUser() {
                parent.dialog({
                    id: 'user_dialog',
                    title : '添加用户',
                    href : '/aclUser/add',
                    width : 440,
                    height : 300,
                    buttons : [ {
                            text : '保存',
                            handler : function() {                                
                                parent.saveUser('/aclUser/add','add');
                            }
                        } ],
                });
            }
            
            function editUser() {
                var rows = $('#user_datagrid').datagrid('getSelections');
                if (rows.length == 1) {
                    var userId= rows[0].id;
//                    console.info('userId:'+rows[0].name);
                    parent.dialog({
                        id: 'user_dialog',
                        title : '修改用户',
                        href : '/aclUser/edit/'+userId,
                        width : 440,
                        height : 300,
                        buttons : [ {
                                text : '保存',
                                iconCls:'icon-save',
                                handler : function() {
                                    parent.saveUser('/aclUser/edit/'+userId,'edit');
                                }
                            } ],
                    });
                } else if (rows.length > 1) {
                    parent.messagerAlert('提示', '同一时间只能编辑一条记录！', 'error');
                } else {
                    parent.messagerAlert('提示', '请选择要编辑的记录！', 'error');
                }
            }
            
             function editUserPop() {
                var rows = $('#user_datagrid').datagrid('getSelections');
                if (rows.length == 1) {
                    var userId= rows[0].id;
                    parent.dialog({
                        id: 'user_dialog',
                        title : '修改用户',
                        href : '/aclUser/edit/'+userId,
                        width : 500,
                        height : 300,
                        buttons : [ {
                                text : '保存',
                                iconCls:'icon-save',
                                handler : function() {
                                    parent.saveUser('/aclUser/edit/'+userId,'edit');
                                }
                            } ],
                    });
                } else if (rows.length > 1) {
                    parent.messagerAlert('提示', '同一时间只能编辑一条记录！', 'error');
                } else {
                    parent.messagerAlert('提示', '请选择要编辑的记录！', 'error');
                }
            }

            
            function removeUser() {
                var rows = $('#user_datagrid').datagrid('getChecked');
                var ids = [];
                if (rows.length > 0) {
                    $.messager.confirm('确认', '您是否要删除当前选中的项目？', function(r) {
                        if (r) {
                            for ( var i = 0; i < rows.length; i++) {
                                ids.push(rows[i].id);
                            }
                            $.ajax({
                                url : '/aclUser/del',
                                data : {
                                    ids : ids.join(',')
                                },
                                method: 'get',
                                dataType : 'json',
                                success : function(r) {
                                    $('#user_datagrid').datagrid('load');
                                    $('#user_datagrid').datagrid('unselectAll');
                                    $.messager.show({
                                        title : '提示',
                                        msg : r.msg
                                    });
                                }
                            });
                        }
                    });
                } else {
                    $.messager.show({
                        title : '提示',
                        msg : '请勾选要删除的记录！'
                    });
                }
            }
            
            //            var toolbar=[{  
            //                    text:'Add',  
            //                    iconCls:'icon-add',  
            //                    handler:function(){append();}  
            //                },{  
            //                    text:'Cut',  
            //                    iconCls:'icon-cut',  
            //                    handler:function(){alert('cut')}  
            //                },'-',{  
            //                    text:'Save',  
            //                    iconCls:'icon-save',  
            //                    handler:function(){alert('save')}  
            //                }] ;
        </script>
{% endblock %}

{% block boby %}
    <body  class="easyui-layout" data-options="fit:true">

        <div data-options="region:'north',title:'查询条件',border:false" style="height: 100px;">
            <form id="user_searchForm">
                检索用户名称(可模糊查询)：<input name="userName" /> 
                <a href="#" class="easyui-linkbutton" data-options="iconCls:'icon-search',plain:true" onclick="searchUser()">查询</a> 
                <a href="#" class="easyui-linkbutton" data-options="iconCls:'icon-cancel',plain:true" onclick="clear()">清空</a>
            </form>
        </div>

        <div data-options="region:'center',border:false" style="overflow: hidden;">
            <table class="easyui-datagrid" id="user_datagrid"    
                   data-options="rownumbers:true,
                   singleSelect:true, 
                   fit : true, 
                   method: 'get',
                   fitColumns : true,
                   url:'/aclUser/find',
                   idField : 'id',
                   pagination : true,
                   border:false,
                   toolbar:'#toolbar' ">  
                <thead>  
                    <tr>  
                        <th data-options="field:'id',checkbox:true,width:30">ID</th>  
                        <th data-options="field:'code',width:40">用户编号</th>  
                        <th data-options="field:'name',width:80,align:'right'">用户名称</th>  
                        <th data-options="field:'department',width:80,align:'right'">部门名称</th>  
                        <th data-options="field:'birthday',width:80,align:'right'">生日</th>  
                    </tr>  
                </thead>  
            </table>  
        </div>
        <div id="toolbar" style="height:auto">  
            <a href="javascript:void(0)" class="easyui-linkbutton" data-options="iconCls:'icon-add',plain:true" onclick="addUser()">新增</a>  
            <a href="javascript:void(0)" class="easyui-linkbutton" data-options="iconCls:'icon-remove',plain:true" onclick="removeUser()">删除</a>  
            <a href="javascript:void(0)" class="easyui-linkbutton" data-options="iconCls:'icon-edit',plain:true" onclick="editUser()">修改1</a> 
            <a href="javascript:void(0)" class="easyui-linkbutton" data-options="iconCls:'icon-edit',plain:true" onclick="editUserPop()">修改2</a>
        </div>
    </body>
{% endblock %}

src/easyoa/templates/aclUser_pop.html
<div style="padding: 5px;overflow: hidden;">
    <form id="user_form" method="post">{% csrf_token %}
        <p>{{ form.code.label }}: {{ form.code }}</p>
        <p>{{ form.name.label }}: {{ form.name }}</p>
        <p>{{ form.department.label }}: {{ form.department }}
            <a href="javascript:void(0)" class="easyui-linkbutton" data-options="iconCls:'icon-search',plain:true" onclick="queryDepartment()"></a>
        </p>
        <p>{{ form.birthday.label }}: {{ form.birthday }}</p>
    </form>
</div>

<script type="text/javascript">   
    function saveUser(url,action) {
        var f = $('#user_form').form();
        $('#user_form').form('submit', {
            url: url,
            success: function(r) {
                var obj = jQuery.parseJSON(r);
                if (obj.success) {
                    var d = getFrameComponent('#user_datagrid');
                    //                    console.info(d);
                    if (action=='edit') {
                        d.datagrid('updateRow', {
                            index: d.datagrid('getRowIndex', obj.obj.id),
                            row: obj.obj
                        });
                    } else {
                        d.datagrid('insertRow', {
                            index: 0,
                            row: obj.obj
                        });
                    }
                    d.datagrid('selectRecord', obj.obj.id);
                    $('#user_dialog').dialog('close');
                }
                $.messager.show({
                    title: '提示',
                    msg: obj.msg
                });
            },
        });
    }  

    function queryDepartment() {
        dialog({
               id: 'department_query',
               title: '查询部门',
               href: '/department/query',
               width: 700,
               height: 450,
               buttons: [{
                     text: '确定',
                     handler: function() {
                           var rows = $('#department_datagrid').datagrid('getChecked');
                           if (rows.length > 0) {
                                     $('#id_department').combogrid('setValue', rows[0].id);
                              }
                           $('#department_query').dialog('close');
                        }
               }],
              });
    }    
</script>

src/easyoa/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <script src="/resources/jslib/boot.js" type="text/javascript"></script> 
        <script src="/resources/js/djangoajax.js" type="text/javascript"></script> 
        {% block js %}
        {% endblock %}
    </head>
    {% block boby %}
    <body class="easyui-layout">
        <div data-options="region:'north'" style="height:60px;"></div>
        <div data-options="region:'west',title:'功能导航',split:true" style="width:400px;">
            {% block tree %}
            {% endblock %}
        </div>
        <div data-options="region:'center',title:''" style="overflow: hidden;">
            {% block center %}
            {% endblock %}
        </div>
    </body>
    {% endblock %}
</html>

src/easyoa/templates/department.html
{% extends "base.html" %}

{% block js %}
        <script type="text/javascript">

            function searchDepartment() {
                $('#department_datagrid').datagrid('load', serializeObject($('#department_searchForm')));
            }
           
            function clear() {
                $('#admin_yhgl_layout input[name=departmentName]').val('');
                $('#department_datagrid').datagrid('load', {});
            }
            
            function addDepartment() {
                parent.dialog({
                    id: 'department_dialog',
                    title : '添加用户',
                    href : '/department/add',
                    width : 440,
                    height : 200,
                    buttons : [ {
                            text : '保存',
                            handler : function() {
                                parent.saveDepartment('/department/add','add');
                            }
                        } ],
                    onLoad : function() {
                        parent.setState();                        
                    }
                });
            }
            
            function editDepartment() {
                var rows = $('#department_datagrid').datagrid('getSelections');
                if (rows.length == 1) {
                    var departmentId= rows[0].id;
                    parent.dialog({
                        id: 'department_dialog',
                        title : '修改部门',
                        href : '/department/edit/'+departmentId,
                        width : 440,
                        height : 200,
                        buttons : [ {
                                text : '保存',
                                handler : function() {
                                    parent.saveDepartment('/department/edit/'+departmentId,'edit');
                                }
                            } ],
                        onLoad : function() {
                            parent.setState();                        
                        }
                    });
                } else if (rows.length > 1) {
                    parent.messagerAlert('提示', '同一时间只能编辑一条记录！', 'error');
                } else {
                    parent.messagerAlert('提示', '请选择要编辑的记录！', 'error');
                }
            }
            
            function removeDepartment() {
                var rows = $('#department_datagrid').datagrid('getChecked');
                var ids = [];
                if (rows.length > 0) {
                    $.messager.confirm('确认', '您是否要删除当前选中的项目？', function(r) {
                        if (r) {
                            for ( var i = 0; i < rows.length; i++) {
                                ids.push(rows[i].id);
                            }
                            $.ajax({
                                url : '/department/del',
                                data : {
                                    ids : ids.join(',')
                                },
                                dataType : 'json',
                                method: 'get',
                                success : function(r) {
                                    console.info('result:'+r.success);                                
                                    if(r.success){
                                        $('#department_datagrid').datagrid('load');
                                        $('#department_datagrid').datagrid('unselectAll');                                        
                                    }
                                    $.messager.show({
                                        title : '提示',
                                        msg : r.msg
                                    });
                                },
                                error:function (XMLHttpRequest, textStatus, errorThrown) {
//                                    $.messager.show({
//                                        title : '提示',
//                                        msg : XMLHttpRequest.responseText
//                                    });
                                    alert(XMLHttpRequest.responseText);
                                }
                            });
                        }
                    });
                } else {
                    $.messager.show({
                        title : '提示',
                        msg : '请勾选要删除的记录！'
                    });
                }
            }
            
        </script>
    </head>
{% endblock %}

{% block boby %}
    <body  class="easyui-layout" data-options="fit:true">

        <div data-options="region:'north',title:'查询条件',border:false" style="height: 100px;">
            <form id="department_searchForm">
                检索部门名称(可模糊查询)：<input name="departmentName" /> 
                <a href="#" class="easyui-linkbutton" data-options="iconCls:'icon-search',plain:true" onclick="searchDepartment()">查询</a> 
                <a href="#" class="easyui-linkbutton" data-options="iconCls:'icon-cancel',plain:true" onclick="clear()">清空</a>
            </form>
        </div>

        <div data-options="region:'center',border:false" style="overflow: hidden;">
            <!--            <table id="admin_yhgl_datagrid"></table>-->

            <table class="easyui-datagrid" id="department_datagrid"    
                   data-options="rownumbers:true,
                   singleSelect:true, 
                   fit : true, 
                   fitColumns : true,
                   url:'/department/find',
                   idField : 'id',
                   method: 'get',
                   pagination : true,
                   border:false,
                   toolbar:'#toolbar' ">  
                <thead>  
                    <tr>  
                        <th data-options="field:'id',checkbox : true,width:80">ID</th>  
                        <th data-options="field:'code',width:100">部门编号</th>  
                        <th data-options="field:'name',width:80,align:'right'">部门名称</th>  
                    </tr>  
                </thead>  
            </table>  
        </div>
        <div id="toolbar" style="height:auto">  
            <a href="javascript:void(0)" class="easyui-linkbutton" data-options="iconCls:'icon-add',plain:true" onclick="addDepartment()">新增</a>  
            <a href="javascript:void(0)" class="easyui-linkbutton" data-options="iconCls:'icon-remove',plain:true" onclick="removeDepartment()">删除</a>  
            <a href="javascript:void(0)" class="easyui-linkbutton" data-options="iconCls:'icon-edit',plain:true" onclick="editDepartment()">修改</a> 
        </div>
    </body>
{% endblock %}

src/easyoa/templates/department_pop.html
<div style="padding: 5px;overflow: hidden;">
    <form id="department_form" method="post">{% csrf_token %}
        {{ form.as_p }}
    </form>
</div>

<script type="text/javascript">
    function saveDepartment(url,action) {
        var f =  $('#department_form').form();
        $('#department_form').form('submit', {
            url : url,
            success : function(r) {
                var obj = jQuery.parseJSON(r);
                if (obj.success) {
                    var d=getFrameComponent('#department_datagrid');
                    //                    console.info(d);
                    if(action=='edit'){
                        d.datagrid('updateRow',{
                            index:d.datagrid('getRowIndex',obj.obj.id),
                            row:obj.obj
                        });
                    }else{
                        d.datagrid('insertRow',{
                            index:0,
                            row:obj.obj
                        });
                    }
                    d.datagrid('selectRecord',obj.obj.id);
                    $('#department_dialog').dialog('close');
                }
                $.messager.show({
                    title : '提示',
                    msg : obj.msg
                });
            }
        });
    }
    
</script>

src/easyoa/templates/department_query.html
<script type="text/javascript">

        function searchDepartment() {
            $('#department_datagrid').datagrid('load', serializeObject($('#department_searchForm')));
        }
     
            
</script>
<div  class="easyui-layout" data-options="fit:true">

    <div data-options="region:'north',title:'',border:false" style="height: 30px;">
        <form id="department_searchForm">
            检索部门名称(可模糊查询)：<input name="departmentName" /> 
            <a href="#" class="easyui-linkbutton" data-options="iconCls:'icon-search',plain:true" onclick="searchDepartment()">查询</a> 
            <a href="#" class="easyui-linkbutton" data-options="iconCls:'icon-cancel',plain:true" onclick="clear()">清空</a>
        </form>
    </div>

    <div data-options="region:'center',border:false" style="overflow: hidden;">
        <!--            <table id="admin_yhgl_datagrid"></table>-->

        <table class="easyui-datagrid" id="department_datagrid"    
               data-options="rownumbers:true,
               singleSelect:true, 
               fit : true, 
               fitColumns : true,
               url:'/department/find',
               idField : 'id',
               method: 'get',
               pagination : true,
               border:false ">  
            <thead>  
                <tr>  
                    <th data-options="field:'id',checkbox : true,width:80">ID</th>  
                    <th data-options="field:'code',width:100">部门编号</th>  
                    <th data-options="field:'name',width:80,align:'right'">部门名称</th>  
                </tr>  
            </thead>  
        </table>  
    </div>
</div>